spring.application.name=FlightTicketBookingSystem
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://localhost:3306/flightdb
spring.datasource.username=flightDB_user
spring.datasource.password=user1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
amedeus.api.key = 1234-5678-9012-3456
amedeus.api.secret = abcd-efgh-ijkl-mnop
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080
logging.level.org.springframework.security=DEBUG

